#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 17, 2019 11:38:32 PM IST  platform: Linux

import sys
import tkinter.messagebox
import mysql.connector
import re
import subprocess
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

mydb=mysql.connector.connect(host="localhost",user="root",passwd="",database="NetworkGuard")
mycursor=mydb.cursor()

import first_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    first_support.init(root, top)
    root.resizable(0,0)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    first_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

# n=StringVar()
# p=StringVar()

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'


        def check():
            name=self.Entry2.get()
            p=self.Entry1.get()
            mycursor.execute("""Select Password from Login where Username = %s""",(name,))
            result=mycursor.fetchall()
            if(len(result)==0):
                tkinter.messagebox.showinfo("Error","Wrong Credentials")
            else:
                sqlpass="%s"%(result[0])
                if(sqlpass==p):
                    root.destroy()
                    subprocess.Popen(['python3','second.py'])
                    #tkinter.messagebox.showinfo("Info","Succesfully Logged in!")
                else:
                    tkinter.messagebox.showerror("Error","Wrong Credentials")


        top.geometry("600x450+430+153")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1, 1)
        top.title("NetworkGuard")
        top.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=-0.017, rely=-0.022, relheight=1.024
                , relwidth=1.018)
        self.Canvas1.configure(background="#020202")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")

        self.Entry1 = tk.Entry(self.Canvas1)
        self.Entry1.place(relx=0.442, rely=0.412,height=32, relwidth=0.288)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="-family {Noto Serif Display} -size 14")
        self.Entry1.configure(selectbackground="#ffffff")
        self.Entry1.configure(show="*")

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.245, rely=0.304, height=32, width=112)
        self.Label1.configure(activebackground="#0f0f0f")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(activeforeground="#ffffff")
        self.Label1.configure(background="#020202")
        self.Label1.configure(disabledforeground="#a3a1a1")
        self.Label1.configure(font="-family {Noto Sans Display} -size 15 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d8d8d8")
        self.Label1.configure(text='''Username :''')

        self.Label2 = tk.Label(self.Canvas1)
        self.Label2.place(relx=0.262, rely=0.412, height=30, width=99)
        self.Label2.configure(activebackground="#ffffff")
        self.Label2.configure(activeforeground="#ffffff")
        self.Label2.configure(background="#020202")
        self.Label2.configure(font="-family {Noto Sans Display} -size 14 -weight bold")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''Password :''')

        self.Entry2 = tk.Entry(self.Canvas1)
        self.Entry2.place(relx=0.442, rely=0.304,height=32, relwidth=0.288)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="-family {Noto Sans Display} -size 14")
        self.Entry2.configure(selectbackground="#ffffff")

        self.Button1 = tk.Button(self.Canvas1)
        self.Button1.place(relx=0.393, rely=0.542, height=40, width=88)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(background="#0a0a0a")
        self.Button1.configure(font="-family {Noto Sans Display} -size 14 -weight bold")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(text='''Login''',command=check)

        self.Label3 = tk.Label(self.Canvas1)
        self.Label3.place(relx=0.065, rely=0.087, height=43, width=523)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#000000")
        self.Label3.configure(font="-family {Noto Sans Display} -size 21 -weight bold")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(text='''Welcome to NetworkGuard''')

if __name__ == '__main__':
    vp_start_gui()





