#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Nov 18, 2019 04:25:37 AM IST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



    menu .pop46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop46" "Popupmenu1" vTcl:WidgetProc "" 1
    menu .pop47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop47" "Popupmenu2" vTcl:WidgetProc "" 1

proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m56" -background #000000 -highlightbackground #050505 
    wm focusmodel $top passive
    wm geometry $top 898x630+199+78
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Dashboard"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab44 \
        -background #000000 \
        -font {-family {Noto Sans Display} -size 22 -weight bold -underline 1} \
        -foreground #ffffff -text {Dashboard for Security Analysis Tools} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground #ffffff -background #000000 \
        -font {-family {Noto Sans Display} -size 14} -foreground #f9f9f9 \
        -highlightcolor black -text {Fetch IP} 
    vTcl:DefineAlias "$top.but52" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -background #000000 -font {-family {Noto Sans Display} -size 14} \
        -foreground #ffffff \
        -text {|------------- Available Networking Tools -------------|} 
    vTcl:DefineAlias "$top.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m56
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    button $top.but57 \
        -background #000000 \
        -font {-family {Noto Sans Display} -size 14 -weight bold} \
        -foreground #ffffff -highlightcolor black -text A.R.P 
    vTcl:DefineAlias "$top.but57" "Button2" vTcl:WidgetProc "Toplevel1" 1
    listbox $top.lis58 \
        -background white -font {-family {Noto Sans Display} -size 14} \
        -foreground $vTcl(actual_gui_fg) -height 36 -width 164 
    .top42.lis58 configure -font "-family {Noto Sans Display} -size 14"
    .top42.lis58 insert end text
    vTcl:DefineAlias "$top.lis58" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but59 \
        -background #000000 \
        -font {-family {Noto Sans Display} -size 14 -weight bold} \
        -foreground #ffffff -highlightcolor black -text TCPdump 
    vTcl:DefineAlias "$top.but59" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but60 \
        -background #020202 \
        -font {-family {Noto Sans Display} -size 14 -weight bold} \
        -foreground #ffffff -highlightcolor black -text NetStat 
    vTcl:DefineAlias "$top.but60" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but61 \
        -background #050505 \
        -font {-family {Noto Sans Display} -size 14 -weight bold} \
        -foreground #ffffff -highlightcolor black -text NSLookup 
    vTcl:DefineAlias "$top.but61" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but62 \
        -background #050505 \
        -font {-family {Noto Sans Display} -size 14 -weight bold} \
        -foreground #ffffff -highlightcolor black -text HPing3 
    vTcl:DefineAlias "$top.but62" "Button6" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes63 \
        -background #000000 -font {-family {Noto Sans Display} -size 10} \
        -foreground #ffffff -highlightcolor black \
        -text {The address resolution protocol (arp) is a protocol used by the Internet Protocol (IP) [RFC826], specifically IPv4, to map IP network addresses to the hardware addresses used by a data link protocol.} \
        -width 162 
    vTcl:DefineAlias "$top.mes63" "Message1" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes64 \
        -background #000000 -font {-family {Noto Sans Display} -size 10} \
        -foreground #ffffff -highlightcolor black \
        -text {hping is a TCP/IP packet assembler/analyzer.It supports TCP, UDP, ICMP and RAW-IP protocols, has a traceroute mode, the ability to send files between a covered channel, and many other features} \
        -width 152 
    vTcl:DefineAlias "$top.mes64" "Message2" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes65 \
        -background #020202 -font {-family {Noto Sans Display} -size 10} \
        -foreground #ffffff -highlightcolor black \
        -text {TCPdump is a powerful command-line packet analyzer; and libpcap, a portable C/C++ library for network traffic capture.} \
        -width 134 
    vTcl:DefineAlias "$top.mes65" "Message3" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes66 \
        -background #000000 -font {-family {Noto Sans Display} -size 10} \
        -foreground #ffffff -highlightcolor black \
        -text {netstat (network statistics) is a network utility that displays network connections for TCP(both incoming and outgoing), routing tables, and a number of network interface and network protocol statistics.} \
        -width 154 
    vTcl:DefineAlias "$top.mes66" "Message4" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes67 \
        -background #020202 -font {-family {Noto Sans Display} -size 10} \
        -foreground #ffffff -highlightcolor black \
        -text {nslookup is a network administration tool available in many computer operating systems for querying the Domain Name System (DNS) to obtain domain name or IP address mapping, or other DNS records. The name "nslookup" means "name server lookup".} \
        -width 174 
    vTcl:DefineAlias "$top.mes67" "Message5" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 190 -y 20 -width 571 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 410 -y 120 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 240 -y 220 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 60 -y 310 -anchor nw -bordermode ignore 
    place $top.lis58 \
        -in $top -x 380 -y 170 -width 164 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 210 -y 310 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 390 -y 310 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 560 -y 310 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 760 -y 310 -anchor nw -bordermode ignore 
    place $top.mes63 \
        -in $top -x 20 -y 380 -width 162 -relwidth 0 -height 205 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes64 \
        -in $top -x 730 -y 380 -width 152 -relwidth 0 -height 205 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.mes65 \
        -in $top -x 200 -y 380 -width 134 -relwidth 0 -height 206 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.mes66 \
        -in $top -x 360 -y 380 -width 154 -relwidth 0 -height 205 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.mes67 \
        -in $top -x 540 -y 380 -width 174 -relwidth 0 -height 210 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

